on: [pull_request]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Package Lock Changes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package Lock Changes
        uses: ./
        with:
          path: 'package-lock.lock'
          token: ${{ secrets.GITHUB_TOKEN }}
